import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountryGreetingsService {


  greetings_array = [
    { country: 'Afghanistan', hellow_text: 'سلام' },
    { country: 'Albania', hellow_text: 'Përshëndetje' },
    { country: 'Algeria', hellow_text: 'مرحبا' },
    { country: 'American Samoa', hellow_text: 'Hello' },
    { country: 'Andorra', hellow_text: 'Hola' },
    { country: 'Angola', hellow_text: 'Olá' },
    { country: 'Anguilla', hellow_text: 'Hello' },
    { country: 'Antigua and Barbuda', hellow_text: 'Hello' },
    { country: 'Argentina', hellow_text: 'Hola' },
    { country: 'Armenia', hellow_text: 'Բարեւ' },
    { country: 'Aruba', hellow_text: 'Hallo' },
    { country: 'Australia', hellow_text: 'Hello' },
    { country: 'Azerbaijan', hellow_text: 'Salam' },
    { country: 'Bahamas', hellow_text: 'Hello' },
    { country: 'Bahrain', hellow_text: 'مرحبا' },
    { country: 'Bangladesh', hellow_text: 'হ্যালো' },
    { country: 'Barbados', hellow_text: 'Hello' },
    { country: 'Belarus', hellow_text: 'добры дзень' },
    { country: 'Belgium', hellow_text: 'Hallo' },
    { country: 'Belize', hellow_text: 'Hello' },
    { country: 'Benin', hellow_text: 'Bonjour' },
    { country: 'Bermuda', hellow_text: 'Hello' },
    { country: 'Bhutan', hellow_text: 'Kuzu zangpo la' },
    { country: 'Bolivia (Plurinational State of)', hellow_text: 'Hola' },
    { country: 'Bosnia and Herzegovina', hellow_text: 'zdravo' },
    { country: 'Botswana', hellow_text: 'Hello' },
    { country: 'Brazil', hellow_text: 'Olá' },
    { country: 'British Indian Ocean Territory', hellow_text: 'Hello' },
    { country: 'Virgin Islands (British)', hellow_text: 'Hello' },
    { country: 'Virgin Islands (U.S.)', hellow_text: 'Hello' },
    { country: 'Brunei Darussalam', hellow_text: 'Hello' },
    { country: 'Bulgaria', hellow_text: 'Здравейте' },
    { country: 'Burkina Faso', hellow_text: 'Bonjour' },
    { country: 'Burundi', hellow_text: 'Bonjour' },
    { country: 'Cambodia', hellow_text: 'ជំរាបសួរ' },
    { country: 'Cameroon', hellow_text: 'Hello' },
    { country: 'Canada', hellow_text: 'Hello' },
    { country: 'Cabo Verde', hellow_text: 'Olá' },
    { country: 'Cayman Islands', hellow_text: 'Hello' },
    { country: 'Central African Republic', hellow_text: 'Bonjour' },
    { country: 'Chile', hellow_text: 'Hola' },
    { country: 'China', hellow_text: '您好' },
    { country: 'Colombia', hellow_text: 'Hola' },
    { country: 'Comoros', hellow_text: 'Bonjour' },
    { country: 'Congo', hellow_text: 'Bonjour' },
    { country: 'Congo (Democratic Republic of the)', hellow_text: 'Bonjour' },
    { country: 'Cook Islands', hellow_text: 'Hello' },
    { country: 'Costa Rica', hellow_text: 'Hola' },
    { country: 'Croatia', hellow_text: 'zdravo' },
    { country: 'Cuba', hellow_text: 'Hola' },
    { country: 'Cuba', hellow_text: 'Hola' },
    { country: 'Cyprus', hellow_text: 'Merhaba' },
    { country: 'Czech Republic', hellow_text: 'Ahoj' },
    { country: 'Denmark', hellow_text: 'Hej' },
    { country: 'Djibouti', hellow_text: 'Bonjour' },
    { country: 'Dominica', hellow_text: 'Hello' },
    { country: 'Dominican Republic', hellow_text: 'Hola' },
    { country: 'Ecuador', hellow_text: 'Hola' },
    { country: 'Egypt', hellow_text: 'مرحبا' },
    { country: 'El Salvador', hellow_text: 'Hola' },
    { country: 'Equatorial Guinea', hellow_text: 'Hola' },
    { country: 'Eritrea', hellow_text: 'Hello' },
    { country: 'Estonia', hellow_text: 'Tere' },
    { country: 'Ethiopia', hellow_text: 'ሰላም' },
    { country: 'Falkland Islands (Malvinas)', hellow_text: 'Hello' },
    { country: 'Faroe Islands', hellow_text: 'Halló' },
    { country: 'Fiji', hellow_text: 'Hello' },
    { country: 'Finland', hellow_text: 'Hei' },
    { country: 'France', hellow_text: 'Bonjour' },
    { country: 'French Guiana', hellow_text: 'Bonjour' },
    { country: 'French Polynesia', hellow_text: 'Bonjour' },
    { country: 'Gabon', hellow_text: 'Bonjour' },
    { country: 'Gambia', hellow_text: 'Hello' },
    { country: 'Georgia', hellow_text: 'გამარჯობა' },
    { country: 'Germany', hellow_text: 'Hallo' },
    { country: 'Ghana', hellow_text: 'Hello' },
    { country: 'Gibraltar', hellow_text: 'Hello' },
    { country: 'Greece', hellow_text: 'Γεια σας' },
    { country: 'Greenland', hellow_text: 'Aluu' },
    { country: 'Grenada', hellow_text: 'Hello' },
    { country: 'Guadeloupe', hellow_text: 'Bonjour' },
    { country: 'Guam', hellow_text: 'Hello' },
    { country: 'Guatemala', hellow_text: 'Hola' },
    { country: 'Guinea', hellow_text: 'Bonjour' },
    { country: 'Guinea-Bissau', hellow_text: 'Olá' },
    { country: 'Guyana', hellow_text: 'Hello' },
    { country: 'Haiti', hellow_text: 'Bonjour' },
    { country: 'Holy See', hellow_text: 'Bonjour' },
    { country: 'Honduras', hellow_text: 'Hola' },
    { country: 'Hong Kong', hellow_text: 'Hello' },
    { country: 'Hungary', hellow_text: 'Helló' },
    { country: 'Iceland', hellow_text: 'Halló' },
    { country: 'India', hellow_text: 'नमस्ते' },
    { country: 'Indonesia', hellow_text: 'Halo' },
    { country: "Côte d'Ivoire", hellow_text: 'Bonjour' },
    { country: 'Iran (Islamic Republic of)', hellow_text: 'سلام' },
    { country: 'Iraq', hellow_text: 'مرحبا' },
    { country: 'Ireland', hellow_text: 'Dia duit' },
    { country: 'Israel', hellow_text: 'שלום' },
    { country: 'Italy', hellow_text: 'Ciao' },
    { country: 'Jamaica', hellow_text: 'Hello' },
    { country: 'Japan', hellow_text: 'こんにちは' },
    { country: 'Jordan', hellow_text: 'مرحبا' },
    { country: 'Kazakhstan', hellow_text: 'Сәлем' },
    { country: 'Kenya', hellow_text: 'Hello' },
    { country: 'Kiribati', hellow_text: 'Hello' },
    { country: 'Kuwait', hellow_text: 'مرحبا' },
    { country: 'Kyrgyzstan', hellow_text: 'салам' },
    { country: "Lao People's Democratic Republic", hellow_text: 'ສະບາຍດີ' },
    { country: 'Latvia', hellow_text: 'Labdien!' },
    { country: 'Lebanon', hellow_text: 'مرحبا' },
    { country: 'Lesotho', hellow_text: 'Hello' },
    { country: 'Liberia', hellow_text: 'Hello' },
    { country: 'Libya', hellow_text: 'مرحبا' },
    { country: 'Liechtenstein', hellow_text: 'Hallo' },
    { country: 'Lithuania', hellow_text: 'Sveiki' },
    { country: 'Luxembourg', hellow_text: 'Bonjour' },
    { country: 'Macao', hellow_text: '您好' },
    { country: 'Macedonia (the former Yugoslav Republic of)', hellow_text: 'Здраво' },
    { country: 'Madagascar', hellow_text: 'Bonjour' },
    { country: 'Malawi', hellow_text: 'Hello' },
    { country: 'Malaysia', hellow_text: 'Salaam' },
    { country: 'Maldives', hellow_text: 'Përshëndetje' },
    { country: 'Mali', hellow_text: 'Bonjour' },
    { country: 'Malta', hellow_text: 'Hello' },
    { country: 'Marshall Islands', hellow_text: 'Hello' },
    { country: 'Martinique', hellow_text: 'Bonjour' },
    { country: 'Mauritania', hellow_text: 'مرحبا' },
    { country: 'Mauritius', hellow_text: 'Hello' },
    { country: 'Mayotte', hellow_text: 'Bonjour' },
    { country: 'Mexico', hellow_text: 'Hola' },
    { country: 'Micronesia (Federated States of)', hellow_text: 'Hello' },
    { country: 'Moldova (Republic of)', hellow_text: 'Alo' },
    { country: 'Monaco', hellow_text: 'Bonjour' },
    { country: 'Mongolia', hellow_text: 'Сайн байна уу' },
    { country: 'Montenegro', hellow_text: 'Здраво' },
    { country: 'Montserrat', hellow_text: 'Hello' },
    { country: 'Morocco', hellow_text: 'مرحبا' },
    { country: 'Mozambique', hellow_text: 'Olá' },
    { country: 'Myanmar', hellow_text: 'မင်္ဂလာပါ' },
    { country: 'Namibia', hellow_text: 'Hello' },
    { country: 'Nauru', hellow_text: 'Hello' },
    { country: 'Nepal', hellow_text: 'नमस्ते' },
    { country: 'Netherlands', hellow_text: 'Hallo' },
    { country: 'New Caledonia', hellow_text: 'Bonjour' },
    { country: 'New Zealand', hellow_text: 'Hello' },
    { country: 'Nicaragua', hellow_text: 'Hola' },
    { country: 'Niger', hellow_text: 'Bonjour' },
    { country: 'Nigeria', hellow_text: 'Hello' },
    { country: 'Niue', hellow_text: 'Hello' },
    { country: 'Norfolk Island', hellow_text: 'Hello' },
    { country: "Korea (Democratic People's Republic of)", hellow_text: '안녕하세요.' },
    { country: 'Northern Mariana Islands', hellow_text: 'Hello' },
    { country: 'Norway', hellow_text: 'Hallo' },
    { country: 'Oman', hellow_text: 'مرحبا' },
    { country: 'Pakistan', hellow_text: 'Hello' },
    { country: 'Palau', hellow_text: 'Hello' },
    { country: 'Palestine, State of', hellow_text: 'مرحبا' },
    { country: 'Panama', hellow_text: 'Hola' },
    { country: 'Papua New Guinea', hellow_text: 'Hello' },
    { country: 'Paraguay', hellow_text: 'Hola' },
    { country: 'Peru', hellow_text: 'Hola' },
    { country: 'Philippines', hellow_text: 'Hello' },
    { country: 'Poland', hellow_text: 'Cześć' },
    { country: 'Portugal', hellow_text: 'Olá' },
    { country: 'Puerto Rico', hellow_text: 'Hola' },
    { country: 'Qatar', hellow_text: 'مرحبا' },
    { country: 'Republic of Kosovo', hellow_text: 'Përshëndetje' },
    { country: 'Réunion', hellow_text: 'Bonjour' },
    { country: 'Romania', hellow_text: 'Alo' },
    { country: 'Russian Federation', hellow_text: 'привет' },
    { country: 'Rwanda', hellow_text: 'Muraho' },
    { country: 'Saint Barthélemy', hellow_text: 'Bonjour' },
    { country: 'Saint Helena, Ascension and Tristan da Cunha', hellow_text: 'Hello' },
    { country: 'Saint Kitts and Nevis', hellow_text: 'Hello' },
    { country: 'Saint Lucia', hellow_text: 'Hello' },
    { country: 'Saint Martin (French part)', hellow_text: 'Hello' },
    { country: 'Saint Pierre and Miquelon', hellow_text: 'Bonjour' },
    { country: 'Saint Vincent and the Grenadines', hellow_text: 'Hello' },
    { country: 'Samoa', hellow_text: 'Talofa' },
    { country: 'San Marino', hellow_text: 'Ciao' },
    { country: 'Sao Tome and Principe', hellow_text: 'Olá' },
    { country: 'Saudi Arabia', hellow_text: 'مرحبا' },
    { country: 'Senegal', hellow_text: 'Bonjour' },
    { country: 'Serbia', hellow_text: 'Здраво' },
    { country: 'Seychelles', hellow_text: 'Bonjour' },
    { country: 'Sierra Leone', hellow_text: 'Hello' },
    { country: 'Singapore', hellow_text: 'Hello' },
    { country: 'Singapore', hellow_text: 'Hello' },
    { country: 'Slovakia', hellow_text: 'ahoj' },
    { country: 'Slovenia', hellow_text: 'Pozdravljeni' },
    { country: 'Solomon Islands', hellow_text: 'Hello' },
    { country: 'Somalia', hellow_text: 'مرحبا' },
    { country: 'South Africa', hellow_text: 'Hello' },
    { country: 'Korea (Republic of)', hellow_text: '안녕하세요.' },
    { country: 'Spain', hellow_text: 'Hola' },
    { country: 'Sri Lanka', hellow_text: 'ආයුබෝවන්' },
    { country: 'Sudan', hellow_text: 'مرحبا' },
    { country: 'Suriname', hellow_text: 'Hallo' },
    { country: 'Swaziland', hellow_text: 'Hello' },
    { country: 'Sweden', hellow_text: 'Hallå' },
    { country: 'Switzerland', hellow_text: 'Hallo' },
    { country: 'Syrian Arab Republic', hellow_text: 'مرحبا' },
    { country: 'Taiwan', hellow_text: '您好' },
    { country: 'Tajikistan', hellow_text: 'Салом' },
    { country: 'Tanzania, United Republic of', hellow_text: 'Hello' },
    { country: 'Thailand', hellow_text: 'สวัสดี' },
    { country: 'Timor-Leste', hellow_text: 'Olá' },
    { country: 'Togo', hellow_text: 'Bonjour' },
    { country: 'Tokelau', hellow_text: 'Hello' },
    { country: 'Tonga', hellow_text: 'Hello' },
    { country: 'Trinidad and Tobago', hellow_text: 'Hello' },
    { country: 'Tunisia', hellow_text: 'مرحبا' },
    { country: 'Turkey', hellow_text: 'Merhaba' },
    { country: 'Turkmenistan', hellow_text: 'Salam' },
    { country: 'Turks and Caicos Islands', hellow_text: 'Hello' },
    { country: 'Tuvalu', hellow_text: 'Hello' },
    { country: 'Uganda', hellow_text: 'Hello' },
    { country: 'Ukraine', hellow_text: 'Здрастуйте' },
    { country: 'United Arab Emirates', hellow_text: 'مرحبا' },
    { country: 'United Kingdom of Great Britain and Northern Ireland', hellow_text: 'Hello' },
    { country: 'United States of America', hellow_text: 'Hello' },
    { country: 'Uruguay', hellow_text: 'Hola' },
    { country: 'Uzbekistan', hellow_text: 'Salom' },
    { country: 'Vanuatu', hellow_text: 'Hello' },
    { country: 'Venezuela (Bolivarian Republic of)', hellow_text: 'Hola' },
    { country: 'Viet Nam', hellow_text: 'Xin chào' },
    { country: 'Wallis and Futuna', hellow_text: 'Bonjour' },
    { country: 'Yemen', hellow_text: 'مرحبا' },
    { country: 'Zambia', hellow_text: 'Hello' },
    { country: 'Zimbabwe', hellow_text: 'Hello' }
  ];
  constructor() { }


  // merge() {
  //   let all_data = [];
  //   let all_data_n = [];
  //   for (let item of this.laguages_arry) {
  //     const arry_data = this.hello_text.filter((obj) => obj.language == item.language.name);
  //     if (arry_data.length == 1) {
  //       const ht = {
  //         "country": item.name,
  //         "hellow_text": arry_data[0].hello
  //       };
  //       all_data.push(ht);
  //     } else {
  //       console.log(item)
  //       const ht = {
  //         "country": item.name,
  //         "hellow_text": 'Hello'
  //       };
  //       all_data_n.push(ht);
  //     }
  //     console.log(all_data_n)
  //     console.log(all_data)
  //   }
  // }
}
